import { spawn } from "node:child_process";
import { AudioPlayerStatus, VoiceConnectionStatus, createAudioPlayer, createAudioResource, entersState, joinVoiceChannel, NoSubscriberBehavior, StreamType } from "@discordjs/voice";
const ffmpegPath = process.env.FFMPEG_PATH || "ffmpeg";
export class RadioService {
  constructor(client, streamUrl) { this.client=client;this.streamUrl=streamUrl;this.player=createAudioPlayer({behaviors:{noSubscriber:NoSubscriberBehavior.Play}});this.connection=null;this.process=null;this.channelId=null;this.restartTimer=null;this.player.on("stateChange",(oldState,newState)=>console.log(`Radio player: ${oldState.status} -> ${newState.status}`));this.player.on(AudioPlayerStatus.Idle,()=>this.scheduleRestart());this.player.on("error",e=>{console.error("Radio player error:",e.message);this.scheduleRestart();}); }
  async diagnoseFfmpeg(){return new Promise((resolve)=>{const child=spawn(ffmpegPath,["-version"],{stdio:["ignore","pipe","pipe"]});let output="";child.stdout.on("data",data=>output+=data);child.once("error",error=>{console.error(`FFmpeg unavailable at '${ffmpegPath}': ${error.message}`);resolve(false);});child.once("exit",code=>{if(code===0){console.log(`Radio FFmpeg: ${output.split(/\r?\n/,1)[0]} (${ffmpegPath})`);resolve(true);}else{console.error(`FFmpeg version check exited with code ${code}.`);resolve(false);}});});}
  async connect(channel){this.stop();if(!await this.diagnoseFfmpeg())throw new Error("FFmpeg is not installed in this Railway deployment.");this.channelId=channel.id;this.connection=joinVoiceChannel({channelId:channel.id,guildId:channel.guild.id,adapterCreator:channel.guild.voiceAdapterCreator,selfDeaf:false});this.connection.on("stateChange",(oldState,newState)=>console.log(`Radio voice: ${oldState.status} -> ${newState.status}`));this.connection.on(VoiceConnectionStatus.Disconnected,()=>this.scheduleRestart());await entersState(this.connection,VoiceConnectionStatus.Ready,20000);this.connection.subscribe(this.player);this.play();console.log(`Radio connected in #${channel.name} (${channel.id}).`);}
  play(){if(!this.connection||!this.channelId)return;this.killProcess();this.process=spawn(ffmpegPath,["-hide_banner","-loglevel","warning","-reconnect","1","-reconnect_streamed","1","-reconnect_delay_max","5","-i",this.streamUrl,"-vn","-af","volume=0.8","-c:a","libopus","-b:a","128k","-ar","48000","-ac","2","-f","ogg","pipe:1"],{windowsHide:true,stdio:["ignore","pipe","pipe"]});this.process.stderr.on("data",data=>console.error(`Radio FFmpeg: ${data.toString().trim()}`));this.process.once("error",error=>{console.error("Could not start radio FFmpeg:",error.message);this.scheduleRestart();});this.process.once("exit",(code,signal)=>{if(this.channelId){console.error(`Radio FFmpeg exited (${code??signal}).`);this.scheduleRestart();}});this.player.play(createAudioResource(this.process.stdout,{inputType:StreamType.OggOpus}));}
  scheduleRestart(){if(!this.channelId||this.restartTimer)return;this.restartTimer=setTimeout(async()=>{this.restartTimer=null;try{if(this.connection?.state.status===VoiceConnectionStatus.Ready){this.play();return;}const c=await this.client.channels.fetch(this.channelId);if(c?.isVoiceBased())await this.connect(c);}catch(e){console.error("Radio reconnect failed:",e.message);this.scheduleRestart();}},5000);}
  stop(){this.channelId=null;if(this.restartTimer)clearTimeout(this.restartTimer);this.restartTimer=null;this.killProcess();this.player.stop();if(this.connection)this.connection.destroy();this.connection=null;}
  killProcess(){if(this.process&&!this.process.killed)this.process.kill();this.process=null;}
}
