import { spawn } from "node:child_process";
import ffmpegPath from "ffmpeg-static";
import { AudioPlayerStatus, VoiceConnectionStatus, createAudioPlayer, createAudioResource, entersState, joinVoiceChannel, NoSubscriberBehavior, StreamType } from "@discordjs/voice";
export class RadioService {
  constructor(client, streamUrl) { this.client=client;this.streamUrl=streamUrl;this.player=createAudioPlayer({behaviors:{noSubscriber:NoSubscriberBehavior.Play}});this.connection=null;this.process=null;this.channelId=null;this.restartTimer=null;this.player.on(AudioPlayerStatus.Idle,()=>this.scheduleRestart());this.player.on("error",e=>{console.error("Radio player error:",e.message);this.scheduleRestart();}); }
  async connect(channel){this.stop();this.channelId=channel.id;this.connection=joinVoiceChannel({channelId:channel.id,guildId:channel.guild.id,adapterCreator:channel.guild.voiceAdapterCreator,selfDeaf:true});this.connection.on(VoiceConnectionStatus.Disconnected,()=>this.scheduleRestart());await entersState(this.connection,VoiceConnectionStatus.Ready,20000);this.connection.subscribe(this.player);this.play();}
  play(){if(!this.connection||!this.channelId)return;this.killProcess();this.process=spawn(ffmpegPath,["-hide_banner","-loglevel","error","-reconnect","1","-reconnect_streamed","1","-reconnect_delay_max","5","-i",this.streamUrl,"-vn","-c:a","libopus","-b:a","128k","-ar","48000","-ac","2","-f","ogg","pipe:1"],{windowsHide:true,stdio:["ignore","pipe","ignore"]});this.process.once("exit",()=>this.scheduleRestart());this.player.play(createAudioResource(this.process.stdout,{inputType:StreamType.OggOpus}));}
  scheduleRestart(){if(!this.channelId||this.restartTimer)return;this.restartTimer=setTimeout(async()=>{this.restartTimer=null;try{const c=await this.client.channels.fetch(this.channelId);if(c?.isVoiceBased())await this.connect(c);}catch(e){console.error("Radio reconnect failed:",e.message);this.scheduleRestart();}},5000);}
  stop(){if(this.restartTimer)clearTimeout(this.restartTimer);this.restartTimer=null;this.killProcess();this.player.stop();if(this.connection)this.connection.destroy();this.connection=null;this.channelId=null;}
  killProcess(){if(this.process&&!this.process.killed)this.process.kill();this.process=null;}
}
